"""
report_generator.py
--------------------
Builds a downloadable PDF summarizing a single prediction result.
"""

import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

RISK_COLORS = {
    "Low": colors.HexColor("#2e7d32"),
    "Medium": colors.HexColor("#ef6c00"),
    "High": colors.HexColor("#c62828"),
}


def generate_pdf_report(result, image_path, output_path, patient_note=""):
    """
    result: dict from inference.predict()
    image_path: path to the uploaded retinal image (embedded in the PDF)
    output_path: where to save the .pdf
    """
    doc = SimpleDocTemplate(output_path, pagesize=letter,
                             topMargin=0.6 * inch, bottomMargin=0.6 * inch)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Title"], fontSize=20, textColor=colors.HexColor("#1a237e")
    )
    heading_style = ParagraphStyle(
        "HeadingStyle", parent=styles["Heading2"], fontSize=13, spaceBefore=12, spaceAfter=6
    )
    body_style = styles["BodyText"]

    elements = []

    elements.append(Paragraph("Diabetic Retinopathy Screening Report", title_style))
    elements.append(Paragraph(
        f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M')}", styles["Normal"]
    ))
    elements.append(Spacer(1, 0.25 * inch))

    # Retinal image
    if os.path.exists(image_path):
        img = Image(image_path, width=2.5 * inch, height=2.5 * inch)
        elements.append(img)
        elements.append(Spacer(1, 0.2 * inch))

    # Result summary table
    risk_color = RISK_COLORS.get(result["risk"], colors.black)
    summary_data = [
        ["Predicted Class", result["class"]],
        ["Risk Level", result["risk"]],
        ["Confidence", f"{result['confidence']}%"],
    ]
    table = Table(summary_data, colWidths=[2 * inch, 3.5 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e8eaf6")),
        ("TEXTCOLOR", (1, 1), (1, 1), risk_color),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 1), (1, 1), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 0.25 * inch))

    elements.append(Paragraph("Description", heading_style))
    elements.append(Paragraph(result["description"], body_style))

    elements.append(Paragraph("Recommendation", heading_style))
    elements.append(Paragraph(result["recommendation"], body_style))

    # All class scores
    elements.append(Paragraph("Confidence Breakdown by Class", heading_style))
    score_rows = [["Class", "Confidence"]] + [
        [k, f"{v}%"] for k, v in result["all_scores"].items()
    ]
    score_table = Table(score_rows, colWidths=[3 * inch, 2 * inch])
    score_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#3949ab")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
    ]))
    elements.append(score_table)

    if patient_note:
        elements.append(Spacer(1, 0.2 * inch))
        elements.append(Paragraph("Notes", heading_style))
        elements.append(Paragraph(patient_note, body_style))

    elements.append(Spacer(1, 0.4 * inch))
    disclaimer = (
        "<i>Disclaimer: This report is generated by an automated screening tool and is "
        "not a substitute for professional medical diagnosis. Please consult a licensed "
        "ophthalmologist for a definitive evaluation.</i>"
    )
    elements.append(Paragraph(disclaimer, ParagraphStyle(
        "Disclaimer", parent=styles["Normal"], fontSize=8, textColor=colors.grey
    )))

    doc.build(elements)
    return output_path
